name: Build and Push to Runpod Registry

on:
  push:
    tags:
      - 'v*'            # build on version tags (e.g. v1.2.3)
    branches:
      - main            # also build on main
  workflow_dispatch:     # allow manual runs

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    env:
      # --- You only change these two if you rename things ---
      REGISTRY: registry.runpod.net
      NAMESPACE: CREATO-GENAI                 # your Runpod org/namespace (UI may show CAPS)
      IMAGE_NAME: creatogen-photoshoot-worker # image repo name you want
      TAG: ${{ github.ref_type == 'tag' && github.ref_name || 'main' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Normalize for Docker (always lowercase)
        run: |
          echo "NAMESPACE_LC=$(echo '${{ env.NAMESPACE }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "IMAGE_NAME_LC=$(echo '${{ env.IMAGE_NAME }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Runpod Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          # Secrets you added in GitHub:
          username: ${{ secrets.RUNPOD_REGISTRY_USER }}  # must be: runpod
          password: ${{ secrets.RUNPOD_REGISTRY_PASS }}  # your rpa_... API key

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.NAMESPACE_LC }}/${{ env.IMAGE_NAME_LC }}:${{ env.TAG }}
            ${{ env.REGISTRY }}/${{ env.NAMESPACE_LC }}/${{ env.IMAGE_NAME_LC }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false

      - name: Show pushed tags (for logs)
        run: |
          echo "Pushed:"
          echo " - ${{ env.REGISTRY }}/${{ env.NAMESPACE_LC }}/${{ env.IMAGE_NAME_LC }}:${{ env.TAG }}"
          echo " - ${{ env.REGISTRY }}/${{ env.NAMESPACE_LC }}/${{ env.IMAGE_NAME_LC }}:latest"
