name: Build and Push to Runpod Registry

on:
  push:
    tags:
      - 'v*'         # builds on releases like v1.0.0
    branches:
      - main         # also build on pushes to main
  workflow_dispatch:  # allow manual runs

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    env:
      REGISTRY: registry.runpod.net
      # 👉 Your Runpod org/namespace slug (use lowercase)
      NAMESPACE: creato-genai
      # 👉 Image name you want under that namespace
      IMAGE_NAME: creatogen-photoshoot-worker
      # Use the tag name when building from a release, otherwise "main"
      TAG: ${{ github.ref_type == 'tag' && github.ref_name || 'main' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Runpod Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.RUNPOD_REGISTRY_USER }}
          password: ${{ secrets.RUNPOD_REGISTRY_PASS }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
            ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false
